// أسماء دول العالم بالعربية — مفهرسة حسب تسمية Natural Earth 110m
export const COUNTRY_AR: Record<string, string> = {
  Afghanistan: "أفغانستان",
  Albania: "ألبانيا",
  Algeria: "الجزائر",
  Angola: "أنغولا",
  Antarctica: "القارة القطبية الجنوبية",
  Argentina: "الأرجنتين",
  Armenia: "أرمينيا",
  Australia: "أستراليا",
  Austria: "النمسا",
  Azerbaijan: "أذربيجان",
  Bahamas: "جزر البهاما",
  Bangladesh: "بنغلاديش",
  Belarus: "بيلاروسيا",
  Belgium: "بلجيكا",
  Belize: "بليز",
  Benin: "بنين",
  Bhutan: "بوتان",
  Bolivia: "بوليفيا",
  "Bosnia and Herz.": "البوسنة والهرسك",
  Botswana: "بوتسوانا",
  Brazil: "البرازيل",
  Brunei: "بروناي",
  Bulgaria: "بلغاريا",
  "Burkina Faso": "بوركينا فاسو",
  Burundi: "بوروندي",
  Cambodia: "كمبوديا",
  Cameroon: "الكاميرون",
  Canada: "كندا",
  "Central African Rep.": "جمهورية أفريقيا الوسطى",
  Chad: "تشاد",
  Chile: "تشيلي",
  China: "الصين",
  Colombia: "كولومبيا",
  Congo: "جمهورية الكونغو",
  "Costa Rica": "كوستاريكا",
  Croatia: "كرواتيا",
  Cuba: "كوبا",
  Cyprus: "قبرص",
  Czechia: "التشيك",
  "Côte d'Ivoire": "ساحل العاج",
  "Dem. Rep. Congo": "الكونغو الديمقراطية",
  Denmark: "الدنمارك",
  Djibouti: "جيبوتي",
  "Dominican Rep.": "جمهورية الدومينيكان",
  Ecuador: "الإكوادور",
  Egypt: "مصر",
  "El Salvador": "السلفادور",
  "Eq. Guinea": "غينيا الاستوائية",
  Eritrea: "إريتريا",
  Estonia: "إستونيا",
  eSwatini: "إسواتيني",
  Ethiopia: "إثيوبيا",
  "Falkland Is.": "جزر فوكلاند",
  Fiji: "فيجي",
  Finland: "فنلندا",
  "Fr. S. Antarctic Lands": "الأراضي الفرنسية الجنوبية",
  France: "فرنسا",
  Gabon: "الغابون",
  Gambia: "غامبيا",
  Georgia: "جورجيا",
  Germany: "ألمانيا",
  Ghana: "غانا",
  Greece: "اليونان",
  Greenland: "غرينلاند",
  Guatemala: "غواتيمالا",
  Guinea: "غينيا",
  "Guinea-Bissau": "غينيا بيساو",
  Guyana: "غيانا",
  Haiti: "هايتي",
  Honduras: "هندوراس",
  Hungary: "المجر",
  Iceland: "آيسلندا",
  India: "الهند",
  Indonesia: "إندونيسيا",
  Iran: "إيران",
  Iraq: "العراق",
  Ireland: "أيرلندا",
  Israel: "إسرائيل",
  Italy: "إيطاليا",
  Jamaica: "جامايكا",
  Japan: "اليابان",
  Jordan: "الأردن",
  Kazakhstan: "كازاخستان",
  Kenya: "كينيا",
  Kosovo: "كوسوفو",
  Kuwait: "الكويت",
  Kyrgyzstan: "قيرغيزستان",
  Laos: "لاوس",
  Latvia: "لاتفيا",
  Lebanon: "لبنان",
  Lesotho: "ليسوتو",
  Liberia: "ليبيريا",
  Libya: "ليبيا",
  Lithuania: "ليتوانيا",
  Luxembourg: "لوكسمبورغ",
  Madagascar: "مدغشقر",
  Malawi: "مالاوي",
  Malaysia: "ماليزيا",
  Mali: "مالي",
  Mauritania: "موريتانيا",
  Mexico: "المكسيك",
  Moldova: "مولدوفا",
  Mongolia: "منغوليا",
  Montenegro: "الجبل الأسود",
  Morocco: "المغرب",
  Mozambique: "موزمبيق",
  Myanmar: "ميانمار",
  "N. Cyprus": "شمال قبرص التركية",
  Namibia: "ناميبيا",
  Nepal: "نيبال",
  Netherlands: "هولندا",
  "New Caledonia": "كاليدونيا الجديدة",
  "New Zealand": "نيوزيلندا",
  Nicaragua: "نيكاراغوا",
  Niger: "النيجر",
  Nigeria: "نيجيريا",
  "North Korea": "كوريا الشمالية",
  Macedonia: "مقدونيا الشمالية",
  Norway: "النرويج",
  Oman: "عُمان",
  Pakistan: "باكستان",
  Palestine: "فلسطين",
  Panama: "بنما",
  "Papua New Guinea": "بابوا غينيا الجديدة",
  Paraguay: "باراغواي",
  Peru: "بيرو",
  Philippines: "الفلبين",
  Poland: "بولندا",
  Portugal: "البرتغال",
  "Puerto Rico": "بورتوريكو",
  Qatar: "قطر",
  Romania: "رومانيا",
  Russia: "روسيا",
  Rwanda: "رواندا",
  "Saudi Arabia": "السعودية",
  Senegal: "السنغال",
  Serbia: "صربيا",
  "Sierra Leone": "سيراليون",
  Slovakia: "سلوفاكيا",
  Slovenia: "سلوفينيا",
  "Solomon Is.": "جزر سليمان",
  Somalia: "الصومال",
  Somaliland: "أرض الصومال",
  "South Africa": "جنوب أفريقيا",
  "South Korea": "كوريا الجنوبية",
  Spain: "إسبانيا",
  "Sri Lanka": "سريلانكا",
  "S. Sudan": "جنوب السودان",
  Sudan: "السودان",
  Suriname: "سورينام",
  Sweden: "السويد",
  Switzerland: "سويسرا",
  Syria: "سوريا",
  Taiwan: "تايوان",
  Tajikistan: "طاجيكستان",
  Thailand: "تايلاند",
  "Timor-Leste": "تيمور الشرقية",
  Togo: "توغو",
  "Trinidad and Tobago": "ترينيداد وتوباغو",
  Tunisia: "تونس",
  Turkey: "تركيا",
  Turkmenistan: "تركمانستان",
  Uganda: "أوغندا",
  Ukraine: "أوكرانيا",
  "United Arab Emirates": "الإمارات العربية المتحدة",
  "United Kingdom": "المملكة المتحدة",
  "United Republic of Tanzania": "تنزانيا",
  "United States of America": "الولايات المتحدة",
  Uruguay: "أوروغواي",
  Uzbekistan: "أوزبكستان",
  Vanuatu: "فانواتو",
  Venezuela: "فنزويلا",
  Vietnam: "فيتنام",
  "W. Sahara": "الصحراء الغربية",
  Yemen: "اليمن",
  Zambia: "زامبيا",
  Zimbabwe: "زيمبابوي",
};

export function arName(en: string): string {
  return COUNTRY_AR[en] ?? en;
}
