import "dotenv/config";
import { db } from "./index";
import { disputes, treaties, news, serviceRequests, conflicts, wars, aiIntel, countryBriefs, interiorIntel, arabStats } from "./schema";
import { sql } from "drizzle-orm";

const monthsAgo = (n: number) => {
  const d = new Date();
  d.setMonth(d.getMonth() - n);
  return d;
};
const daysAgo = (n: number) => {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d;
};
const hoursAgo = (n: number) => {
  const d = new Date();
  d.setTime(d.getTime() - n * 3600_000);
  return d;
};

async function main() {
  console.log("⏳ تفريغ الجداول القديمة...");
  await db.execute(sql`TRUNCATE TABLE disputes, treaties, news, service_requests, conflicts, wars, ai_intel, country_briefs, interior_intel, arab_country_stats RESTART IDENTITY CASCADE`);

  console.log("⏳ إدراج النزاعات...");
  await db.insert(disputes).values([
    {
      code: "NRD-2025-001",
      title: "أزمة مياه النيل — الملء والتشغيل الأحادي للسد",
      parties: "جمهورية مصر العربية / جمهورية إثيوبيا الفيدرالية",
      type: "water",
      status: "mediation",
      priority: "strategic",
      region: "القرن الأفريقي",
      progress: 64,
      summary: "وساطة رباعية بإشراف الوزارة لضمان اتفاق قانوني مُلزم لقواعد الملء والتشغيل.",
      openedAt: monthsAgo(11),
    },
    {
      code: "NRD-2025-002",
      title: "ترسيم الحدود البحرية ومكامن الغاز شرق المتوسط",
      parties: "مصر / قبرص / اليونان / جهات متنازعة",
      type: "maritime",
      status: "arbitration",
      priority: "strategic",
      region: "شرق المتوسط",
      progress: 78,
      summary: "ملف أمام هيئة تحكيم دولية لتثبيت الحقوق الاقتصادية في المنطقة الاقتصادية الخالصة.",
      openedAt: monthsAgo(10),
    },
    {
      code: "NRD-2025-003",
      title: "التوتر الحدودي — محور رفح ومعبر كرم أبو سالم",
      parties: "قوات حرس الحدود / عناصر مسلحة غير نظامية",
      type: "border",
      status: "active",
      priority: "strategic",
      region: "شمال سيناء",
      progress: 41,
      summary: "تنسيق ميداني مباشر مع وزارة الدفاع لتأمين الشريط الحدودي وضبط المعابر.",
      openedAt: monthsAgo(9),
    },
    {
      code: "NRD-2025-004",
      title: "تأمين خطوط الملاحة الدولية في باب المندب",
      parties: "التحالف البحري الدولي / قوى إقليمية",
      type: "maritime",
      status: "active",
      priority: "high",
      region: "البحر الأحمر",
      progress: 52,
      summary: "آلية تنسيق بحري دولي لحماية الملاحة في قناة السويس وباب المندب.",
      openedAt: monthsAgo(8),
    },
    {
      code: "NRD-2025-005",
      title: "النزاع الاستثماري — امتيازات المنطقة الاقتصادية لقناة السويس",
      parties: "الهيئة العامة للاستثمار / تحالف شركات دولية",
      type: "investment",
      status: "arbitration",
      priority: "high",
      region: "الشرق الأوسط",
      progress: 83,
      summary: "دعوى تحكيم أمام المركز الدولي لتسوية منازعات الاستثمار (ICSID).",
      openedAt: monthsAgo(8),
    },
    {
      code: "NRD-2025-006",
      title: "الوساطة المصرية لوقف إطلاق النار — الملف الليبي",
      parties: "أطراف النزاع الليبية / بعثة الأمم المتحدة",
      type: "diplomatic",
      status: "mediation",
      priority: "strategic",
      region: "شمال أفريقيا",
      progress: 69,
      summary: "مسار القاهرة التفاوضي لتوحيد المؤسسات ووقف الاقتتال غرب الحدود.",
      openedAt: monthsAgo(7),
    },
    {
      code: "NRD-2025-007",
      title: "خلاف الرسوم الجمركية على الصادارات الزراعية",
      parties: "وزارة التجارة والصناعة / كتلة تجارية إقليمية",
      type: "trade",
      status: "negotiation",
      priority: "medium",
      region: "أوروبا",
      progress: 58,
      summary: "مفاوضات ثنائية لتسوية النزاع التجاري قبل اللجوء لمنظمة التجارة العالمية.",
      openedAt: monthsAgo(6),
    },
    {
      code: "NRD-2025-008",
      title: "تنظيم حقوق الصيد في خليج السويس",
      parties: "هيئة الثروة السمكية / شركات صيد أجنبية",
      type: "maritime",
      status: "resolved",
      priority: "low",
      region: "البحر الأحمر",
      progress: 100,
      summary: "تم الفصل بالتسوية الودية وتوقيع بروتوكول تنظيمي جديد.",
      openedAt: monthsAgo(6),
    },
    {
      code: "NRD-2025-009",
      title: "نزاع المجال الجوي — مسارات الطيران فوق شبه جزيرة سيناء",
      parties: "سلطة الطيران المدني / منظمة الإيكاو",
      type: "airspace",
      status: "negotiation",
      priority: "high",
      region: "شمال سيناء",
      progress: 47,
      summary: "معالجة قانونية لتعارض المسارات المدنية مع مناطق العمليات العسكرية.",
      openedAt: monthsAgo(5),
    },
    {
      code: "NRD-2025-010",
      title: "أزمة سحب السفراء والتمثيل الدبلوماسي",
      parties: "وزارة الخارجية / دولة إقليمية",
      type: "diplomatic",
      status: "resolved",
      priority: "medium",
      region: "الشرق الأوسط",
      progress: 100,
      summary: "احتواء الأزمة عبر قنوات الوساطة السرية وعودة التمثيل الكامل.",
      openedAt: monthsAgo(5),
    },
    {
      code: "NRD-2025-011",
      title: "ترسيم الحدود البرية الجنوبية — المثلثات المتنازع عليها",
      parties: "اللجنة المشتركة لترسيم الحدود",
      type: "territorial",
      status: "arbitration",
      priority: "strategic",
      region: "الحدود الجنوبية",
      progress: 72,
      summary: "توثيق الخرائط التاريخية والسندات القانونية أمام لجنة الترسيم الدولية.",
      openedAt: monthsAgo(4),
    },
    {
      code: "NRD-2025-012",
      title: "نزاع عابر للحدود — أنشطة التهريب بالصحراء الغربية",
      parties: "قوات إنفاذ القانون / شبكات تهريب عابرة",
      type: "border",
      status: "active",
      priority: "high",
      region: "الصحراء الغربية",
      progress: 36,
      summary: "غرفة عمليات مشتركة مع المنطقة الغربية العسكرية لتحييد التهديدات.",
      openedAt: monthsAt3(),
    },
    {
      code: "NRD-2025-013",
      title: "تسوية مديونية تجارية متنازع عليها — قطاع البترول",
      parties: "الهيئة العامة للبترول / ائتلاف موردين دوليين",
      type: "trade",
      status: "resolved",
      priority: "medium",
      region: "الشرق الأوسط",
      progress: 100,
      summary: "تسوية نهائية عبر الوساطة الوزارية بجدولة المديونية.",
      openedAt: monthsAgo(3),
    },
    {
      code: "NRD-2025-014",
      title: "حماية خطوط الكابلات البحرية شرق المتوسط",
      parties: "المنطقة الاقتصادية الخالصة / مشغلون دوليون",
      type: "maritime",
      status: "mediation",
      priority: "high",
      region: "شرق المتوسط",
      progress: 61,
      summary: "اتفاق إطاري لحماية البنية التحتية الرقمية العابرة للمياه الإقليمية.",
      openedAt: monthsAgo(2),
    },
    {
      code: "NRD-2025-015",
      title: "النزاع حول أملاك الدولة والتوثيق العقاري الدولي",
      parties: "وزارة العدل / جهات ادعاء أجنبية",
      type: "territorial",
      status: "frozen",
      priority: "low",
      region: "أوروبا",
      progress: 22,
      summary: "ملف مجمّد بانتظار استيفاء المستندات السيادية.",
      openedAt: monthsAgo(1),
    },
    {
      code: "NRD-2025-016",
      title: "تنسيق عبور المساعدات الإنسانية — معبر رفح البري",
      parties: "الهلال الأحمر / وكالات الأمم المتحدة",
      type: "diplomatic",
      status: "active",
      priority: "strategic",
      region: "شمال سيناء",
      progress: 55,
      summary: "تنسيق سيادي لضمان التدفق الآمن للمساعدات عبر الحدود.",
      openedAt: daysAgo(24),
    },
  ]);

  console.log("⏳ إدراج المعاهدات...");
  await db.insert(treaties).values([
    { title: "اتفاقية نيويورك للاعتراف بأحكام المحكمين وتنفيذها", parties: "172 دولة", category: "تحكيم دولي", reference: "TR-1958/NY", status: "سارية", signedAt: monthsAgo(120) },
    { title: "اتفاقية الأمم المتحدة لقانون البحار", parties: "168 دولة", category: "منازعات بحرية", reference: "TR-1982/UNCLOS", status: "سارية", signedAt: monthsAgo(96) },
    { title: "ميثاق الأمم المتحدة — الفصل السادس (الحل السلمي للمنازعات)", parties: "193 دولة", category: "وساطة وتفاوض", reference: "TR-1945/UN6", status: "سارية", signedAt: monthsAgo(150) },
    { title: "اتفاقية سنغافورة بشأن الوساطة", parties: "57 دولة", category: "وساطة دولية", reference: "TR-2019/SG", status: "سارية", signedAt: monthsAgo(30) },
    { title: "اتفاقية ترسيم الحدود البحرية — شرق المتوسط", parties: "مصر / قبرص / اليونان", category: "ترسيم حدود", reference: "TR-2020/MED", status: "سارية", signedAt: monthsAgo(24) },
    { title: "بروتوكول التعاون المشترك لفض النزاعات الحدودية", parties: "مصر / دول الجوار", category: "أمن حدودي", reference: "TR-2022/BRD", status: "سارية", signedAt: monthsAgo(18) },
    { title: "مذكرة تفاهم حوض النيل — آلية التشاور الإقليمي", parties: "دول حوض النيل", category: "مياه عابرة", reference: "TR-2023/NILE", status: "قيد التفعيل", signedAt: monthsAgo(9) },
    { title: "اتفاقية تشجيع وحماية الاستثمارات المتبادلة", parties: "مصر / الاتحاد الأوروبي", category: "منازعات استثمارية", reference: "TR-2021/INV", status: "سارية", signedAt: monthsAgo(40) },
  ]);

  console.log("⏳ إدراج الأخبار والبيانات...");
  await db.insert(news).values([
    {
      title: "الوزارة تعلن نجاح الوساطة الرباعية بشأن قواعد الملء والتشغيل",
      excerpt: "توصلت جولات الوساطة المصرية برعاية الوزارة إلى صيغة توافقية أولية تضمن الحقوق المائية التاريخية وتمنع الضرر الجسيم، وسط إشادة دولية واسعة بالدور المحوري للقاهرة.",
      category: "بيان رسمي",
      image: "/images/summit.jpg",
      urgent: true,
      publishedAt: daysAgo(1),
    },
    {
      title: "توقيع بروتوكول حماية الكابلات البحرية شرق المتوسط بالأحرف الأولى",
      excerpt: "وقّعت الوزارة بالأحرف الأولى بروتوكولًا إطاريًا مع المشغلين الدوليين لحماية البنية التحتية الرقمية العابرة للمياه الإقليمية المصرية، بالتنسيق مع القوات البحرية.",
      category: "معاهدات",
      image: "/images/treaty.jpg",
      urgent: false,
      publishedAt: daysAgo(3),
    },
    {
      title: "غرفة العمليات المشتركة ترفع درجة الجاهزية على المحور الشمالي الشرقي",
      excerpt: "بالتنسيق الكامل مع وزارة الدفاع المصرية، رفعت غرفة العمليات المركزية درجة الاستعداد القصوى لتأمين الشريط الحدودي وتكثيف الدوريات المشتركة.",
      category: "عمليات",
      image: "/images/theater-map.jpg",
      urgent: true,
      publishedAt: daysAgo(5),
    },
    {
      title: "حكم تحكيمي نهائي لصالح مصر في النزاع الاستثماري بقيمة ٢.٤ مليار دولار",
      excerpt: "أصدرت هيئة التحكيم الدولية حكمها النهائي برفض كامل دعاوى الطرف المقابل وتثبيت مشروعية الإجراءات السيادية المصرية في المنطقة الاقتصادية.",
      category: "أحكام دولية",
      image: "/images/hero-building.jpg",
      urgent: false,
      publishedAt: daysAgo(9),
    },
    {
      title: "القاهرة تستضيف الجولة التاسعة لمفاوضات التسوية الشاملة للملف الليبي",
      excerpt: "برعاية وزارة الكشف الدولي لمصر ودول العالم، انطلقت بالقاهرة الجولة التاسعة من مسار التسوية الليبية بمشاركة جميع الأطراف وبعثة الأمم المتحدة للدعم.",
      category: "وساطة",
      image: "/images/summit.jpg",
      urgent: false,
      publishedAt: daysAgo(14),
    },
    {
      title: "إطلاق المنصة الرقمية الموحدة لتوثيق المعاهدات الدولية",
      excerpt: "دشّنت الوزارة منصتها الرقمية السيادية المؤمّنة لتوثيق وأرشفة أكثر من أربعة آلاف معاهدة واتفاقية دولية ببصمة رقمية غير قابلة للتلاعب.",
      category: "خدمات رقمية",
      image: "/images/treaty.jpg",
      urgent: false,
      publishedAt: daysAgo(21),
    },
  ]);

  console.log("⏳ إدراج طلبات الخدمة التجريبية...");
  await db.insert(serviceRequests).values([
    {
      trackingCode: "REQ-2025-78412",
      name: "شركة الملاحة المتحدة ش.م.م",
      organization: "قطاع الشحن البحري",
      email: "legal@unitednav.example",
      phone: "+20 100 000 0000",
      requestType: "تحكيم تجاري دولي",
      subject: "طلب تحكيم في منازعة عقد نقل بحري",
      details: "منازعة تعاقدية مع شركة تفريغ أوروبية حول غرامات التأخير بميناء دمياط.",
      status: "أُحيل لهيئة التحكيم",
      createdAt: daysAgo(6),
    },
    {
      trackingCode: "REQ-2025-78103",
      name: "الاتحاد العام للمصدرين",
      organization: "قطاع التصدير",
      email: "dispute@exporters.example",
      phone: "+20 111 000 0000",
      requestType: "وساطة تجارية",
      subject: "وساطة في نزاع رسوم جمركية",
      details: "طلب وساطة ودية لتسوية نزاع رسوم على شحنات التمور المصرية.",
      status: "قيد الفحص الأمني",
      createdAt: daysAgo(2),
    },
  ]);

  console.log("⏳ إدراج بؤر النزاعات المباشرة...");
  await db.insert(conflicts).values([
    {
      code: "GAZA-OP",
      name: "الحرب على قطاع غزة",
      theater: "قطاع غزة — جنوب فلسطين المحتلة",
      parties: "إسرائيل / حركة حماس والفصائل الفلسطينية",
      intensity: "war",
      statusLabel: "حرب مفتوحة رغم مراحل التهدئة",
      since: "أكتوبر ٢٠٢٣",
      summary: "حرب واسعة النطاق مع حصار خانق وعمليات برية متقطعة، وتفاوض متعثر حول التهدئة والأسرى والإعمار.",
      ministryRole: "الوساطة المصرية المباشرة لوقف إطلاق النار، وتأمين معبر رفح، وإدخال قوافل الإغاثة.",
      latest: "جولة تفاوض جديدة بالقاهرة حول المرحلة الثانية من التهدئة وتبادل الأسرى.",
      affected: "٢.٢ مليون نازح",
      mx: 63,
      my: 20,
      updatedAt: hoursAgo(1),
    },
    {
      code: "SUDAN-WAR",
      name: "الحرب الأهلية السودانية",
      theater: "الخرطوم — دارفور — كردفان",
      parties: "القوات المسلحة السودانية / قوات الدعم السريع",
      intensity: "war",
      statusLabel: "حرب شاملة وكارثة إنسانية",
      since: "أبريل ٢٠٢٣",
      summary: "قتال شامل على المدن الكبرى والمناطق الزراعية مع انهيار الخدمات وتهديد وحدة الدولة السودانية.",
      ministryRole: "مبادرة جوار السودان بالقاهرة، واستضافة مسارات التفاوض، وتسيير جسور الإغاثة البرية.",
      latest: "تصاعد القتال في الفاشر وسط تحذيرات أممية من مجاعة وشيكة.",
      affected: "١١ مليون نازح",
      mx: 61,
      my: 62,
      updatedAt: hoursAgo(3),
    },
    {
      code: "REDSEA-YEM",
      name: "حرب البحر الأحمر — اليمن",
      theater: "باب المندب — الساحل اليمني الغربي",
      parties: "أنصار الله / التحالف الدولي للازدهار البحري",
      intensity: "escalation",
      statusLabel: "ضربات متبادلة وملاحة معطلة",
      since: "تصعيد مستمر منذ ٢٠٢٣",
      summary: "استهداف سفن تجارية وضربات جوية وصاروخية متبادلة أربكت الشريان الملاحي لقناة السويس.",
      ministryRole: "حماية الأمن الملاحي لقناة السويس وقناة الوساطة المصرية العمانية لخفض التصعيد.",
      latest: "إعلان استهداف سفينة جديدة وغارات جوية ردًا عليها قرب الحديدة.",
      affected: "١٥٪ من التجارة العالمية",
      mx: 74,
      my: 62,
      updatedAt: hoursAgo(2),
    },
    {
      code: "IRN-ISR",
      name: "المواجهة الإيرانية الإسرائيلية المباشرة",
      theater: "الأجواء والساحات السيبرانية الإقليمية",
      parties: "إسرائيل / إيران وأذرع المحور",
      intensity: "escalation",
      statusLabel: "قواعد اشتباك جديدة خطرة",
      since: "تصعيد مباشر ٢٠٢٤ — ٢٠٢٥",
      summary: "تبادل ضربات صاروخية ومسيّرة مباشرة بين الطرفين كسر عقود حرب الظل وفتح باب حرب إقليمية محتملة.",
      ministryRole: "غرفة تقييم المخاطر المشتركة مع وزارة الدفاع لحماية العمق الاستراتيجي المصري.",
      latest: "رصد استعدادات صاروخية جديدة وتبادل تهديدات علنية بين الطرفين.",
      affected: "إنذار إقليمي شامل",
      mx: 82,
      my: 8,
      updatedAt: hoursAgo(5),
    },
    {
      code: "SYRIA-TRANS",
      name: "سوريا — بؤر المرحلة الانتقالية",
      theater: "الساحل — الجنوب — الجزيرة",
      parties: "الإدارة السورية الجديدة / فلول وميليشيات مسلحة",
      intensity: "clashes",
      statusLabel: "اشتباكات متقطعة وجيوب توتر",
      since: "ديسمبر ٢٠٢٤",
      summary: "جيوب قتال متقطعة وتوترات طائفية في الساحل والجنوب رغم انتهاء الحرب الكبرى ومساعي إعادة الإعمار.",
      ministryRole: "دعم التسوية الشاملة عبر مسار القاهرة ومنع تجدد الحريق الكبير.",
      latest: "اشتباكات محدودة في ريف اللاذقية ووساطات عشائرية لاحتوائها.",
      affected: "٦.٨ مليون لاجئ",
      mx: 65,
      my: 11,
      updatedAt: hoursAgo(8),
    },
    {
      code: "SOM-AS",
      name: "الصومال — تمرد حركة الشباب",
      theater: "وسط وجنوب الصومال — مقديشو",
      parties: "الحكومة الفيدرالية وقوات أتميس / حركة الشباب",
      intensity: "clashes",
      statusLabel: "هجمات وتفجيرات متصاعدة",
      since: "٢٠٠٧ — تجدد ٢٠٢٥",
      summary: "عمليات برية وجوية ضد الحركة تقابلها تفجيرات في العاصمة وأطراف المدن المحررة.",
      ministryRole: "تنسيق عربي أفريقي لدعم الاستقرار وتأمين ممرات الغذاء عبر البحر الأحمر.",
      latest: "تفجير استهدف نقطة تفتيش حكومية وغارات جوية ردًا عليه في جوبالاند.",
      affected: "٣.٨ مليون نازح",
      mx: 75,
      my: 93,
      updatedAt: hoursAgo(11),
    },
    {
      code: "SSD-NAS",
      name: "جنوب السودان — انهيار توازنات السلام",
      theater: "أعالي النيل — جونقلي",
      parties: "الحكومة الانتقالية / المعارضة المسلحة (SPLM-IO)",
      intensity: "clashes",
      statusLabel: "مواجهات متجددة تهدد اتفاق ٢٠١٨",
      since: "تجدد ٢٠٢٥",
      summary: "مواجهات عسكرية متجددة واعتقالات سياسية تهدد اتفاق السلام الهش وتلوّح بعودة الحرب الأهلية.",
      ministryRole: "وساطة مصرية عبر دول الجوار وربطها بمسار أمن حوض النيل.",
      latest: "قتال في ناصر ودعوات أممية عاجلة لضبط النفس.",
      affected: "٢.٢ مليون لاجئ",
      mx: 60,
      my: 86,
      updatedAt: hoursAgo(15),
    },
    {
      code: "LIBYA-SPLIT",
      name: "ليبيا — الجمود والانقسام المؤسسي",
      theater: "خط سرت — الجفرة",
      parties: "حكومة الوحدة الوطنية / القيادة العامة",
      intensity: "tension",
      statusLabel: "جمود عسكري هش منذ ٢٠٢٠",
      since: "٢٠١١",
      summary: "خطوط تماس ثابتة مع احتقان سياسي ونفوذ مرتزقة أجانب يهدد أي انزلاق نحو المواجهة من جديد.",
      ministryRole: "مسار القاهرة لتوحيد المؤسسة العسكرية وملف الانتخابات المتعثر.",
      latest: "تحشيدات محدودة غرب سرت وتحذيرات بعثة الأمم المتحدة.",
      affected: "٨٠٠ ألف متأثر",
      mx: 39,
      my: 16,
      updatedAt: hoursAgo(20),
    },
    {
      code: "IRAQ-FACT",
      name: "العراق — التوتر مع الفصائل المسلحة",
      theater: "بغداد — الأنبار — أربيل",
      parties: "الفصائل المسلحة / القوات الأمريكية والحكومة العراقية",
      intensity: "tension",
      statusLabel: "هجمات مسيّرات متقطعة",
      since: "تصاعد ٢٠٢٤",
      summary: "هجمات بطائرات مسيّرة وصواريخ على مواقع التحالف تقابلها ضربات محدودة وحذر حكومي من الانزلاق.",
      ministryRole: "قنوات ضبط النفس عبر اللجان الأمنية الثلاثية ومجلس الجامعة.",
      latest: "سقوط مسيّرة قرب قاعدة عين الأسد دون إصابات.",
      affected: "تهديد إقليمي متوسط",
      mx: 74,
      my: 15,
      updatedAt: hoursAgo(26),
    },
    {
      code: "LEB-FRONT",
      name: "الجبهة اللبنانية الجنوبية",
      theater: "جنوب الليطاني — الجليل",
      parties: "حزب الله / الجيش الإسرائيلي",
      intensity: "ceasefire",
      statusLabel: "وقف إطلاق نار هش",
      since: "وقف إطلاق النار نوفمبر ٢٠٢٤",
      summary: "توقف العمليات الكبرى مع خروقات جوية ومدفعية شبه يومية واستحقاقات الانسحاب غير المنجزة.",
      ministryRole: "عضوية آلية الرصد الدولية ودعم تثبيت الهدنة برعاية مصرية.",
      latest: "تبادل اتهامات بخرق الهدنة واجتماع طارئ للجنة الرصد.",
      affected: "٩٦ ألف نازح عادوا جزئيًا",
      mx: 66,
      my: 15,
      updatedAt: hoursAgo(6),
    },
  ]);

  console.log("⏳ إدراج الحروب والنزاعات العالمية...");
  await db.insert(wars).values([
    {
      code: "W-UKR-RUS",
      name: "الحرب الروسية الأوكرانية",
      region: "أوروبا الشرقية",
      intensity: "war",
      statusLabel: "حرب استنزاف واسعة النطاق",
      since: "فبراير ٢٠٢٢",
      sideA: "روسيا الاتحادية",
      sideB: "أوكرانيا",
      belligerents: "روسيا, أوكرانيا",
      iso: "643,804",
      summary: "أكبر حرب برية في أوروبا منذ ١٩٤٥ — خطوط تماس ثابتة في دونباس والجنوب مع ضربات مسيّرة وصاروخية يومية على العمقين.",
      monitorNote: "ترصد الوزارة أثر الحرب على أمن الحبوب في البحر الأسود وخطوط الإمداد نحو مصر.",
      latest: "ضربات مسيّرة مكثفة على منشآت الطاقة الأوكرانية ومفاوضات هشة حول تبادل الأسرى.",
      affected: "١٠.٤ مليون نازح ولاجئ",
      sourceLabel: "ReliefWeb — مكتب الأمم المتحدة OCHA",
      sourceUrl: "https://reliefweb.int/country/ukr",
      lat: 48, lon: 35, updatedAt: hoursAgo(1),
    },
    {
      code: "W-GAZA",
      name: "الحرب على قطاع غزة",
      region: "الشرق الأوسط",
      intensity: "war",
      statusLabel: "حرب وكارثة إنسانية غير مسبوقة",
      since: "أكتوبر ٢٠٢٣",
      sideA: "إسرائيل",
      sideB: "حركة حماس والفصائل الفلسطينية",
      belligerents: "إسرائيل, فلسطين",
      iso: "376,275",
      summary: "حرب مفتوحة في القطاع المحاصر مع تدمير واسع وكارثة إنسانية، ووسطاء يفرضون مراحل تهدئة هشة.",
      monitorNote: "القناة المصرية المركزية للتهدئة ومعبر رفح — تدار الملفات من غرفة القاهرة مباشرة.",
      latest: "مشاورات القاهرة حول المرحلة الثانية من التهدئة وإدخال الإعمار.",
      affected: "١.٩ مليون نازح داخليًا",
      sourceLabel: "ReliefWeb — الأرض الفلسطينية المحتلة",
      sourceUrl: "https://reliefweb.int/country/pse",
      lat: 31, lon: 34, updatedAt: hoursAgo(2),
    },
    {
      code: "W-SUDAN",
      name: "الحرب الأهلية السودانية",
      region: "أفريقيا — وادي النيل",
      intensity: "war",
      statusLabel: "أسوأ أزمة نزوح في العالم",
      since: "أبريل ٢٠٢٣",
      sideA: "القوات المسلحة السودانية (SAF)",
      sideB: "قوات الدعم السريع (RSF)",
      belligerents: "السودان (طرفان داخليان)",
      iso: "729",
      summary: "حرب شاملة بين الجيش والدعم السريع في الخرطوم ودارفور وكردفان أنتجت أكبر أزمة نزوح ومجاعة معلنة.",
      monitorNote: "مبادرة جوار السودان بالقاهرة ومعبر أشكيت للإغاثة تحت إشراف مباشر.",
      latest: "معارك عنيفة حول الفاشر وتحذيرات أممية من اتساع المجاعة.",
      affected: "١٢ مليون نازح — مجاعة معلنة",
      sourceLabel: "ReliefWeb — السودان",
      sourceUrl: "https://reliefweb.int/country/sdn",
      lat: 15, lon: 32, updatedAt: hoursAgo(3),
    },
    {
      code: "W-SAHEL",
      name: "حرب الساحل الكبرى",
      region: "غرب أفريقيا — الساحل",
      intensity: "war",
      statusLabel: "انتشار تمرد جهادي واسع",
      since: "٢٠١٢ — تفاقم ٢٠٢٠",
      sideA: "جيوش مالي وبوركينا فاسو والنيجر",
      sideB: "جماعة نصرة الإسلام (JNIM) وتنظيم داعش",
      belligerents: "مالي, بوركينا فاسو, النيجر",
      iso: "466,854,562",
      summary: "تمرد جهادي متحرك يسيطر على أرياف واسعة من الساحل مع انسحاب القوات الفرنسية ووصول مقاولين جدد.",
      monitorNote: "تهديد مباشر لأمن وادي النيل من الجنوب الغربي — رصد عبر شركاء الساحل.",
      latest: "هجوم واسع لـJNIM على محيط باماكو وتشديد قبضته على الطرق التجارية.",
      affected: "أكثر من ٣ ملايين نازح",
      sourceLabel: "ACLED / ReliefWeb — مالي",
      sourceUrl: "https://reliefweb.int/country/mli",
      lat: 17, lon: 0, updatedAt: hoursAgo(5),
    },
    {
      code: "W-DRC",
      name: "حرب شرق الكونغو الديمقراطية",
      region: "وسط أفريقيا — البحيرات الكبرى",
      intensity: "escalation",
      statusLabel: "تصعيد M23 والمدن الكبرى تحت الخطر",
      since: "تصعيد ٢٠٢٢ — ذروة ٢٠٢٥",
      sideA: "القوات المسلحة الكونغولية (FARDC)",
      sideB: "حركة M23 (بدعم إقليمي موثق أمميًا)",
      belligerents: "الكونغو الديمقراطية, رواندا",
      iso: "180,646",
      summary: "سيطرت M23 على غوما وبوكافو في ٢٠٢٥ وسط إدانة دولية لتدخل رواندي — أزمة معدنية وإنسانية مزمنة.",
      monitorNote: "متابعة عبر شركاء الاتحاد الأفريقي وقناة الوساطة الأنجولية (مسار لواندا).",
      latest: "وقف إطلاق نار هش برعاية قطرية أمريكية بعد جولات الدوحة.",
      affected: "أكثر من ٧ ملايين نازح",
      sourceLabel: "ReliefWeb — الكونغو الديمقراطية",
      sourceUrl: "https://reliefweb.int/country/cod",
      lat: -2, lon: 29, updatedAt: hoursAgo(6),
    },
    {
      code: "W-IRN-ISR",
      name: "المواجهة الإيرانية الإسرائيلية المباشرة",
      region: "الشرق الأوسط",
      intensity: "escalation",
      statusLabel: "تبادل ضربات مباشرة غير مسبوق",
      since: "٢٠٢٤ — حرب الأيام ١٢ في ٢٠٢٥",
      sideA: "إسرائيل",
      sideB: "إيران",
      belligerents: "إسرائيل, إيران",
      iso: "376,364",
      summary: "انتقل العداء من حرب الظل إلى ضربات صاروخية وجوية مباشرة شملت منشآت نووية وعمق المدن قبل تهدئة هشة.",
      monitorNote: "غرفة تقييم المخاطر المشتركة مع وزارة الدفاع لحماية العمق الاستراتيجي المصري.",
      latest: "وقف إطلاق نار هش بعد حرب الأيام الاثني عشر ومخاوف من جولة جديدة حول الملف النووي.",
      affected: "إنذار إقليمي شامل",
      sourceLabel: "CFR Global Conflict Tracker",
      sourceUrl: "https://www.cfr.org/global-conflict-tracker",
      lat: 33, lon: 51, updatedAt: hoursAgo(4),
    },
    {
      code: "W-MYANMAR",
      name: "الحرب الأهلية في ميانمار",
      region: "جنوب شرق آسيا",
      intensity: "war",
      statusLabel: "انهيار سيطرة المجلس العسكري",
      since: "انقلاب فبراير ٢٠٢١",
      sideA: "جيش ميانمار (تاتمادو)",
      sideB: "قوات الدفاع الشعبي (PDF) والجيوش الإثنية",
      belligerents: "ميانمار (أطراف داخلية)",
      iso: "104",
      summary: "تحالفات إثنية ومقاومة شعبية انتزعت مناطق حدودية واسعة من الجيش — حرب استنزاف وجوع في الريف.",
      monitorNote: "متابعة لأثر النزاع على ممرات الطاقة والمخدرات في آسيا.",
      latest: "تقدم جديد للتحالفات الإثنية في ولايتي شان وراخين رغم الزلزال.",
      affected: "٣.٥ مليون نازح",
      sourceLabel: "ReliefWeb — ميانمار",
      sourceUrl: "https://reliefweb.int/country/mmr",
      lat: 21, lon: 96, updatedAt: hoursAgo(8),
    },
    {
      code: "W-REDSEA",
      name: "حرب البحر الأحمر — اليمن",
      region: "البحر الأحمر — الجزيرة العربية",
      intensity: "escalation",
      statusLabel: "الملاحة العالمية تحت الاستهداف",
      since: "تصعيد نوفمبر ٢٠٢٣",
      sideA: "أنصار الله (الحوثيون)",
      sideB: "الولايات المتحدة وبريطانيا وقوات التحالف",
      belligerents: "اليمن, الولايات المتحدة, بريطانيا",
      iso: "887,840,826",
      summary: "هجمات صاروخية ومسيّرة على الشحن في باب المندب وضربات جوية أمريكية بريطانية عميقة الرد.",
      monitorNote: "الأمن الملاحي لقناة السويس على رأس أولويات غرفة العمليات — عائدات الملاحة خط أحمر.",
      latest: "هدنة بحرية هشة عبر الوساطة العمانية وتراجع الهجمات مؤقتًا.",
      affected: "١٨ مليون يمني بحاجة إنسانية",
      sourceLabel: "ReliefWeb — اليمن",
      sourceUrl: "https://reliefweb.int/country/yem",
      lat: 15, lon: 44, updatedAt: hoursAgo(7),
    },
    {
      code: "W-HAITI",
      name: "الانهيار الأمني في هايتي",
      region: "الكاريبي — الأمريكتان",
      intensity: "escalation",
      statusLabel: "العصابات تسيطر على ٨٥٪ من العاصمة",
      since: "١٩٩٠ — انهيار ٢٠٢١",
      sideA: "تحالف العصابات المسلحة (Viv Ansanm)",
      sideB: "الحكومة الانتقالية وبعثة MSS الكينية",
      belligerents: "هايتي, كينيا (بعثة دولية)",
      iso: "332,404",
      summary: "سيطرة عصابات شبه كاملة على بورت أو برنس وانهيار مؤسسات الدولة مع بعثة دولية متعثرة.",
      monitorNote: "دراسة حالة يتابعها مرصد الوزارة لفشل آليات التدخل الدولي.",
      latest: "تحويل البعثة إلى قوة أممية أكبر وتجدد القتال حول القصر الرئاسي.",
      affected: "٧٠٠ ألف نازح",
      sourceLabel: "ReliefWeb — هايتي",
      sourceUrl: "https://reliefweb.int/country/hti",
      lat: 19, lon: -72, updatedAt: hoursAgo(10),
    },
    {
      code: "W-SOMALIA",
      name: "الصومال — تمرد حركة الشباب",
      region: "القرن الأفريقي",
      intensity: "clashes",
      statusLabel: "هجمات وتفجيرات متصاعدة",
      since: "٢٠٠٧",
      sideA: "الحكومة الفيدرالية وقوات ATMIS",
      sideB: "حركة الشباب المرتبطة بالقاعدة",
      belligerents: "الصومال, قوات أفريقية مشتركة",
      iso: "706",
      summary: "حرب عصابات واسعة في الوسط والجنوب مع تفجيرات في مقديشو واستنزاف لقوات حفظ السلام.",
      monitorNote: "تأمين الممرات الغذائية عبر القرن الأفريقي يرتبط مباشرة بأمن البحر الأحمر.",
      latest: "هجوم انتحاري قرب القصر الرئاسي وغارات دقيقة ردًا عليه.",
      affected: "٣.٨ مليون نازح",
      sourceLabel: "ReliefWeb — الصومال",
      sourceUrl: "https://reliefweb.int/country/som",
      lat: 3, lon: 45, updatedAt: hoursAgo(9),
    },
    {
      code: "W-NIGERIA",
      name: "تمرد بوكو حرام — حوض بحيرة تشاد",
      region: "غرب أفريقيا",
      intensity: "clashes",
      statusLabel: "تجديد نشاط الجماعتين ٢٠٢٥",
      since: "٢٠٠٩",
      sideA: "جيوش نيجيريا والنيجر وتشاد والكاميرون",
      sideB: "بوكو حرام وداعش غرب أفريقيا (ISWAP)",
      belligerents: "نيجيريا, النيجر, تشاد, الكاميرون",
      iso: "566,562,148,120",
      summary: "حركتا تمرد تحاصران الأحواض والقرى الحدودية رغم سنوات الحملات العسكرية الرباعية المشتركة.",
      monitorNote: "ملف إقليمي يرتبط بأمن الساحل الغربي الممتد نحو ليبيا.",
      latest: "اشتعال قتال حول معاقل سامبيسا وموجة اختطافات جديدة.",
      affected: "٣ ملايين نازح في الحوض",
      sourceLabel: "ReliefWeb — نيجيريا",
      sourceUrl: "https://reliefweb.int/country/nga",
      lat: 12, lon: 13, updatedAt: hoursAgo(12),
    },
    {
      code: "W-MOZ",
      name: "تمرد كابو ديلغادو — موزمبيق",
      region: "جنوب أفريقيا",
      intensity: "clashes",
      statusLabel: "عودة هجمات بعد تراجع",
      since: "٢٠١٧ — تصاعد ٢٠٢٤",
      sideA: "قوات موزمبيق وقوات SADC الإقليمية",
      sideB: "داعش — موزمبيق (الشباب محليًا)",
      belligerents: "موزمبيق, قوات مجموعة التنمية الجنوبية SADC",
      iso: "508",
      summary: "عصابة مسلحة مرتبطة بداعش تهدد مشروعات الغاز العملاقة شمال البلاد رغم التدخل الرواندي والإقليمي.",
      monitorNote: "متابعة لأثره على أسواق الغاز العالمية وأمن خطوط الإمداد الأفريقية.",
      latest: "انسحاب قوات SADC وسط تصاعد هجمات جديدة في ماسيندا.",
      affected: "١.٣ مليون نازح",
      sourceLabel: "ReliefWeb — موزمبيق",
      sourceUrl: "https://reliefweb.int/country/moz",
      lat: -13, lon: 40, updatedAt: hoursAgo(14),
    },
    {
      code: "W-AFG",
      name: "أفغانستان — طالبان في مواجهة داعش",
      region: "جنوب آسيا",
      intensity: "clashes",
      statusLabel: "عنف منخفض وانهيار إنساني",
      since: "عودة طالبان ٢٠٢١",
      sideA: "حكومة طالبان الفعلية",
      sideB: "داعش — ولاية خراسان (ISKP)",
      belligerents: "أفغانستان (أطراف داخلية)",
      iso: "4",
      summary: "حكم طالبان مستقر أمنيًا نسبيًا لكنه يواجه هجمات خراسان وأزمة جوع وجفاف مزمنة.",
      monitorNote: "ممرات مخدرات وأمن حدودي يرصدها تحليل المرصد بعيد المدى.",
      latest: "هجوم لداعش في كابل وترحيل جماعي للاجئين من دول الجوار.",
      affected: "٢٣ مليونًا بحاجة للمساعدة",
      sourceLabel: "ReliefWeb — أفغانستان",
      sourceUrl: "https://reliefweb.int/country/afg",
      lat: 33, lon: 66, updatedAt: hoursAgo(16),
    },
    {
      code: "W-ETHIOPIA",
      name: "إثيوبيا — تمرد أمهرة وأورومو",
      region: "القرن الأفريقي",
      intensity: "clashes",
      statusLabel: "حرب خفية بعد تيغراي",
      since: "٢٠٢٣",
      sideA: "الحكومة الفيدرالية الإثيوبية",
      sideB: "ميليشيات فانو (أمهرة) وجيش تحرير أورومو",
      belligerents: "إثيوبيا (أطراف داخلية)",
      iso: "231",
      summary: "حرب عصابات متصاعدة في أمهرة وأوروميا بعد أعوام من حرب تيغراي — تعبئة واسعة وقطع للخدمات.",
      monitorNote: "استقرار إثيوبيا عامل حاسم في ملف مياه النيل والوساطة الرباعية الجارية.",
      latest: "معارك في جوجام وخطف جنود اتحاديين على الطريق الشمالي.",
      affected: "٤.٥ مليون نازح داخلي",
      sourceLabel: "ReliefWeb — إثيوبيا",
      sourceUrl: "https://reliefweb.int/country/eth",
      lat: 11, lon: 38, updatedAt: hoursAgo(11),
    },
    {
      code: "W-COLOMBIA",
      name: "تجدد الصراع المسلح في كولومبيا",
      region: "أمريكا الجنوبية",
      intensity: "clashes",
      statusLabel: "انهيار السلام الشامل تدريجيًا",
      since: "عقود — تصاعد ٢٠٢٣",
      sideA: "الحكومة الكولومبية",
      sideB: "جيش التحرير الوطني ELN ومنشقون عن FARC",
      belligerents: "كولومبيا (أطراف داخلية)",
      iso: "170",
      summary: "عودة العمليات الكبرى في كاتاتومبو وكوكا بين الجيش والجماعات المسلحة رغم مسار التفاوض الشامل.",
      monitorNote: "نموذج رصد للتسويات الهشة بين الدولة والجماعات المسلحة.",
      latest: "أزمة نزوح جديدة في كاتاتومبو وتعليق محادثات ELN.",
      affected: "٨٠ ألف نازح في ٢٠٢٥",
      sourceLabel: "ReliefWeb — كولومبيا",
      sourceUrl: "https://reliefweb.int/country/col",
      lat: 3, lon: -73, updatedAt: hoursAgo(18),
    },
    {
      code: "W-PAKISTAN",
      name: "باكستان — تمرد طالبان والبلوش",
      region: "جنوب آسيا",
      intensity: "clashes",
      statusLabel: "أدمى عام منذ عقد",
      since: "تصاعد ٢٠٢١",
      sideA: "الجيش الباكستاني",
      sideB: "طالبان باكستان TTP وجيش تحرير بلوشستان",
      belligerents: "باكستان, أفغانستان (انطلاقًا من)",
      iso: "586",
      summary: "موجة هجمات منطلقة من أفغانستان وخطف قطار جافار إكسبريس في ٢٠٢٥ لحظة فارقة للانهيار الأمني.",
      monitorNote: "ممرات الطاقة الدولية والحدود النووية تجعل الملف عالي الحساسية للرصد.",
      latest: "عمليات عسكرية واسعة في خيبر وبلوشستان وهجمات انتقامية.",
      affected: "زيادة الهجمات ٧٠٪ عام ٢٠٢٤",
      sourceLabel: "ReliefWeb — باكستان",
      sourceUrl: "https://reliefweb.int/country/pak",
      lat: 32, lon: 70, updatedAt: hoursAgo(13),
    },
    {
      code: "W-LIBYA",
      name: "ليبيا — الجمود والانقسام المسلح",
      region: "شمال أفريقيا",
      intensity: "tension",
      statusLabel: "خطوط تماس هشة منذ ٢٠٢٠",
      since: "٢٠١١",
      sideA: "حكومة الوحدة الوطنية (طرابلس)",
      sideB: "القيادة العامة — الجيش الوطني (الشرق)",
      belligerents: "ليبيا (معسكران)",
      iso: "434",
      summary: "معسكران مسلحان يتقاسمان البلاد مع مرتزقة أجانب ونفط كورقة ضغط — حرب توقفت ولم تُحسم.",
      monitorNote: "مسار القاهرة لتوحيد المؤسسة العسكرية — الجوار الليبي خط تماس أول مع مصر.",
      latest: "اشتباكات مسلحة في طرابلس بعد اغتيال قائد ميليشيا.",
      affected: "هشاشة مؤسسية ونفطية شاملة",
      sourceLabel: "CFR Global Conflict Tracker",
      sourceUrl: "https://www.cfr.org/global-conflict-tracker/conflict/instability-libya",
      lat: 27, lon: 17, updatedAt: hoursAgo(15),
    },
    {
      code: "W-TAIWAN",
      name: "توتر مضيق تايوان",
      region: "شرق آسيا",
      intensity: "tension",
      statusLabel: "مناورات تطويق متكررة",
      since: "تصعيد منذ ٢٠٢٢",
      sideA: "الصين",
      sideB: "تايوان",
      belligerents: "الصين, تايوان, الولايات المتحدة (ضمانات)",
      iso: "156,158",
      summary: "مناورات تطويقية وتعديات خط الوسط اليومية مع سباق تسلح وتحشيد أمريكي في غرب المحيط الهادئ.",
      monitorNote: "المضيق يمر عبره خُمس التجارة العالمية — بند مراقبة استراتيجي دائم.",
      latest: "مناورات صينية جديدة حول الجزيرة وتحذيرات أمريكية.",
      affected: "خُمس التجارة العالمية",
      sourceLabel: "CFR Global Conflict Tracker",
      sourceUrl: "https://www.cfr.org/global-conflict-tracker/conflict/confrontation-over-taiwan",
      lat: 24, lon: 120, updatedAt: hoursAgo(20),
    },
    {
      code: "W-KOREA",
      name: "التوتر في شبه الجزيرة الكورية",
      region: "شرق آسيا",
      intensity: "tension",
      statusLabel: "سباق تسلح نووي وباليستي",
      since: "١٩٥٠ — هدنة دون سلام",
      sideA: "كوريا الشمالية",
      sideB: "كوريا الجنوبية والولايات المتحدة",
      belligerents: "كوريا الشمالية, كوريا الجنوبية, الولايات المتحدة",
      iso: "408,410,840",
      summary: "تجارب صاروخية متلاحقة ودفعات قوات شمالية لأوكرانيا رفعت التوتر لمستويات ما قبل ربيع ٢٠١٧.",
      monitorNote: "ملف نووي عالمي يتابعه تحليل المرصد الاستراتيجي.",
      latest: "إطلاق صاروخ متوسط المدى نحو البحر واستنفار ياباني.",
      affected: "سباق تسلح نووي نشط",
      sourceLabel: "CFR Global Conflict Tracker",
      sourceUrl: "https://www.cfr.org/global-conflict-tracker/conflict/north-korea-crisis",
      lat: 39, lon: 127, updatedAt: hoursAgo(17),
    },
    {
      code: "W-CAUCASUS",
      name: "أرمينيا وأذربيجان — سلام هش بعد قره باغ",
      region: "القوقاز",
      intensity: "tension",
      statusLabel: "تفاوض على معاهدة نهائية",
      since: "١٩٨٨ — حسم ٢٠٢٣",
      sideA: "أرمينيا",
      sideB: "أذربيجان",
      belligerents: "أرمينيا, أذربيجان",
      iso: "51,31",
      summary: "بعد استعادة قره باغ في ٢٠٢٣ تتفاوض الدولتان على معاهدة سلام نهائية وسط تبادل اتهامات حدودية.",
      monitorNote: "نموذج جديد لتسوية الصراعات المجمدة يدرسه باحثو الوزارة.",
      latest: "تقدم في نص معاهدة السلام وخلاف على الشرط الدستوري الأرمني.",
      affected: "١٠٠ ألف أرمني نازح",
      sourceLabel: "Crisis Group — CrisisWatch",
      sourceUrl: "https://www.crisisgroup.org/crisiswatch",
      lat: 40, lon: 46, updatedAt: hoursAgo(22),
    },
    {
      code: "W-KASHMIR",
      name: "توتر كشمير — الهند وباكستان",
      region: "جنوب آسيا",
      intensity: "tension",
      statusLabel: "قصف متبادل بعد هجوم باهالغام",
      since: "مواجهة مايو ٢٠٢٥",
      sideA: "الهند",
      sideB: "باكستان",
      belligerents: "الهند, باكستان",
      iso: "356,586",
      summary: "أخطر مواجهة بين القوتين النوويتين منذ ٢٠١٩ — صواريخ ومسيّرات في مايو ٢٠٢٥ قبل وقف إطلاق نار أمريكي.",
      monitorNote: "مواجهة نووية محتملة على رأس قائمة مخاطر المرصد العالمية.",
      latest: "وقف إطلاق نار متماسك مع تراشق إعلامي حول حصيلة الضربات.",
      affected: "خط تماس نووي مباشر",
      sourceLabel: "Crisis Group — CrisisWatch",
      sourceUrl: "https://www.crisisgroup.org/crisiswatch",
      lat: 34, lon: 76, updatedAt: hoursAgo(19),
    },
    {
      code: "W-WSAHARA",
      name: "الصحراء الغربية — الجمود المسلح",
      region: "المغرب العربي",
      intensity: "tension",
      statusLabel: "استئناف المناوشات منذ ٢٠٢٠",
      since: "١٩٧٥",
      sideA: "المغرب",
      sideB: "جبهة البوليساريو",
      belligerents: "المغرب, جبهة البوليساريو (الجمهورية الصحراوية)",
      iso: "504,732",
      summary: "انهارت هدنة ١٩٩١ في ٢٠٢٠ وعادت المناوشات عبر الجدار الرملي وسط انقسام دولي حول الاستفتاء.",
      monitorNote: "ملف قريب من العمق المغاربي يرتبط بأمن الساحل والصحراء.",
      latest: "تبادل اتهامات بخرق منطقة الفاركية والجدار الدفاعي.",
      affected: "١٧٣ ألف لاجئ في مخيمات تندوف",
      sourceLabel: "ReliefWeb — الصحراء الغربية",
      sourceUrl: "https://reliefweb.int/country/esh",
      lat: 24, lon: -13, updatedAt: hoursAgo(21),
    },
  ]);

  console.log("⏳ إدراج النبضات الاستخباراتية الأولية...");
  await db.insert(aiIntel).values([
    { title: "محادثات سلام مكثفة لإنهاء الحرب الأوكرانية وسط ضغوط ميدانية", region: "أوروبا الشرقية", country: "أوكرانيا", severity: "war", summary: "تتواصل الجهود الدولية لبحث مقترحات وقف إطلاق النار الشامل بين موسكو وكييف، وسط استمرار الضربات المتبادلة على البنى التحتية للطاقة وخطوط التماس الشرقية.", source: "ReliefWeb — OCHA", url: "https://reliefweb.int/country/ukr", createdAt: hoursAgo(4) },
    { title: "مراحل جديدة من اتفاق التهدئة في غزة تدخل حيز التنفيذ بوساطة مصرية", region: "الشرق الأوسط", country: "فلسطين", severity: "ceasefire", summary: "تتابع اللجنة المشتركة سير تنفيذ بنود المرحلة الجديدة من التهدئة بما يشمل تبادل الأسرى وتوسيع دخول المساعدات الإنسانية عبر معبر رفح بإشراف مصري.", source: "ReliefWeb — oPt", url: "https://reliefweb.int/country/pse", createdAt: hoursAgo(6) },
    { title: "مجاعة معلنة تتوسع في السودان مع احتدام القتال حول الفاشر", region: "أفريقيا", country: "السودان", severity: "war", summary: "حذرت الأمم المتحدة من اتساع نطاق المجاعة في دارفور مع استمرار الحصار على الفاشر واستحالة وصول قوافل الإغاثة إلى مئات الآلاف من المدنيين.", source: "ReliefWeb — السودان", url: "https://reliefweb.int/country/sdn", createdAt: hoursAgo(8) },
    { title: "عودة حذرة لحركة الملاحة في باب المندب بعد تفاهمات التهدئة", region: "البحر الأحمر", country: "اليمن", severity: "escalation", summary: "سجلت وكالات الشحن الدولية ارتفاعًا نسبيًا في عبور السفن للممر الحيوي عقب إعلان الهدنة البحرية، مع استمرار مرافقة السفن الكبرى من القوات الدولية.", source: "ReliefWeb — اليمن", url: "https://reliefweb.int/country/yem", createdAt: hoursAgo(10) },
    { title: "قتال متصاعد في شمال ميانمار رغم الهدنة الزلزالية المعلنة", region: "آسيا", country: "ميانمار", severity: "war", summary: "تبادل الجيش والتحالفات الإثنية الاتهامات بخرق الهدنة الإنسانية المعلنة عقب الزلزال، مع استمرار العمليات البرية في ولاية شان.", source: "ReliefWeb — ميانمار", url: "https://reliefweb.int/country/mmr", createdAt: hoursAgo(12) },
    { title: "تصعيد لافت لهجمات حركة الشباب في محيط مقديشو", region: "القرن الأفريقي", country: "الصومال", severity: "clashes", summary: "نفذت الحركة سلسلة هجمات متتالية استهدفت مواقع حكومية في العاصمة والأقاليم الوسطى، بالتزامن مع انتشار بعثة الاتحاد الأفريقي الجديدة AUSSOM.", source: "ACLED — Conflict Index", url: "https://acleddata.com/", createdAt: hoursAgo(16) },
    { title: "صدامات حدودية متقطعة شمال كوسوفو تستدعي تدخل كيفور", region: "البلقان", country: "كوسوفو", severity: "tension", summary: "شهدت المعابر الشمالية توترات بين الأهالي الصرب وقوات الأمن، وسط دعوات أوروبية لاستئناف حوار التطبيع المتوقف منذ ٢٠٢٣.", source: "Crisis Group — CrisisWatch", url: "https://www.crisisgroup.org/crisiswatch", createdAt: hoursAgo(20) },
    { title: "قوات مكافحة الإرهاب الإسرائيلية توسع عملياتها في جنين", region: "الشرق الأوسط", country: "الضفة الغربية", severity: "clashes", summary: "شنت القوات الإسرائيلية موجة مداهمات واسعة في مخيم جنين وطولكرم ما أدى لإصابات واعتقالات وإخلاء مئات العائلات من منازلها.", source: "ReliefWeb — oPt", url: "https://reliefweb.int/country/pse", createdAt: hoursAgo(24) },
    { title: "توقيع اتفاق سلام تاريخي بين الدولة والجبهة في الفلبين", region: "آسيا", country: "الفلبين", severity: "ceasefire", summary: "أنهت الحكومة وجبهة مورو أربعة عقود من الصراع المسلح في مينداناو عبر تفعيل كامل لاتفاق الاندماج والحكم الذاتي الإقليمي.", source: "CFR Global Conflict Tracker", url: "https://www.cfr.org/global-conflict-tracker", createdAt: hoursAgo(30) },
  ]);

  console.log("⏳ إدراج منشورات الداخلية الأولية...");
  await db.insert(interiorIntel).values([
    { title: "الداخلية تعلن ضبط تشكيل عصابي بحوزته ٤٨ قطعة سلاح ناري في حملة أمنية نوعية بأسيوط", category: "ضبطيات ومداهمات", severity: "escalation", summary: "نجحت الأجهزة الأمنية في مداهمة بؤرة إجرامية شديدة الخطورة بإحدى قرى الصعيد، وأسفرت العملية عن ضبط عناصر التشكيل وأسلحة متنوعة وكمية من المواد المخدرة قبل ترويجها.", governorate: "أسيوط", source: "اليوم السابع", url: "https://www.youm7.com", image: "/images/interior-raid.jpg", createdAt: hoursAgo(2) },
    { title: "كشف ملابسات واقعة فيديو متداول وضبط المتهمين خلال ٢٤ ساعة من الرصد", category: "بيان رسمي", severity: "clashes", summary: "رصدت الأجهزة المعنية مقطعًا متداولًا على منصات التواصل، وبالفحص الأمني الدقيق تَحقّق تكييف الواقعة وتحديد مرتكبيها وضبطهم واتخاذ الإجراءات القانونية اللازمة حيالهم.", governorate: "القاهرة", source: "أخبار اليوم", url: "https://akhbarelyom.com", image: "/images/interior-press.jpg", createdAt: hoursAgo(4) },
    { title: "حملات مكافحة المخدرات تُحبط تهريب ١.٥ طن مواد مخدرة قبل تسريبها للمنافذ الجنوبية", category: "مكافحة المخدرات", severity: "war", summary: "وردت معلومات أمنية باعتزام تشكيل دولي تهريب شحنة كبيرة، وعقب تقنين الإجراءات وبالتنسيق مع الجهات السيادية تم توقيت الكمين وإحباط المحاولة بكامل أفرادها وعيناتها.", governorate: "أسوان", source: "الوطن", url: "https://www.elwatannews.com", image: "/images/interior-raid.jpg", createdAt: hoursAgo(7) },
    { title: "الإدارة العامة للمرور: ضبط ١٢٤ ألف مخالفة مرورية متنوعة خلال ٢٤ ساعة", category: "المرور والحماية", severity: "tension", summary: "شملت الحملات الميدانية على الطرق السريعة والمحاور الكبرى مخالفات السرعة الزائدة وقيادة تحت تأثير مواد مخدرة والحمولات الزائدة، استمرارًا لفرض الانضباط المروري وحماية أرواح المواطنين.", governorate: "على مستوى الجمهورية", source: "مصراوي", url: "https://www.masrawy.com", image: "/images/interior-patrol.jpg", createdAt: hoursAgo(9) },
    { title: "مباحث السياحة والآثار تستعيد ٩٦ قطعة أثرية بحوزة متهمَين بالإسكندرية", category: "مضبوطات سيادية", severity: "escalation", summary: "تَمكنت الحملة من ضبط شخصين تخصصا في الاتجار غير المشروع في القطع الأثرية، وأُحيلا إلى النيابة العامة وأُودعت المضبوطات قيد التحفظ لصالح المجلس الأعلى للآثار.", governorate: "الإسكندرية", source: "بوابة الأهرام", url: "https://gate.ahram.org.eg", image: "/images/interior-raid.jpg", createdAt: hoursAgo(13) },
    { title: "قوات الحماية المدنية تسيطر على حريق واسع داخل عقار تجاري دون خسائر بشرية", category: "الحماية المدنية", severity: "clashes", summary: "انتقلت سيارات الإطفاء والإنقاذ فور تلقي البلاغ، وتمت السيطرة على النيران قبل امتدادها للمباني المجاورة وإخلاء قاطني العقار بسلام كامل قبل انهيار جزئي للواجهة.", governorate: "الجيزة", source: "الدستور", url: "https://www.dostor.org", image: "/images/interior-patrol.jpg", createdAt: hoursAgo(18) },
    { title: "مديرية أمن القاهرة تعلن اكتمال خطة التأمين الشاملة للميادين والمنشآت الحيوية", category: "بيان رسمي", severity: "tension", summary: "أكدت القيادات الأمنية جاهزية الخدمات المعينة وكاميرات المراقبة والتمركزات الثابتة والمتحركة، مع تفعيل غرفة القيادة المشتركة على مدار الساعة لاستقبال البلاغات فورًا.", governorate: "القاهرة", source: "أخبار اليوم", url: "https://akhbarelyom.com", image: "/images/interior-press.jpg", createdAt: hoursAgo(26) },
    { title: "ضبط بؤرة لتصنيع الألعاب النارية ومصادرة ٣ أطنان خامات خطرة قبل موسم الأعياد", category: "ضبطيات ومداهمات", severity: "clashes", summary: "أسفرت المداهمة عن تفكيك ورشة غير مرخصة داخل مبنى سكني وضبط مالكها والكميات كاملة، وجارٍ اتخاذ الإجراءات قانونًا بتهمة تعريض حياة المواطنين للخطر.", governorate: "المنيا", source: "المصري اليوم", url: "https://www.almasryalyoum.com", image: "/images/interior-raid.jpg", createdAt: hoursAgo(31) },
  ]);

  console.log("⏳ إدراج قاعدة بيانات الوضع الإنساني العربي...");
  await db.insert(arabStats).values([
    { country: "سوريا", colors: "#ce1126,#f5f0e6,#161616", status: "مرحلة انتقالية هشة", displaced: "نحو ٦.٨ مليون نازح داخلي (أعلى نسبة عالميًا)", refugeesOut: "٥.١ مليون لاجئ بالخارج", deaths: "نحو ٥٨٠ ألفًا منذ ٢٠١١ (المرصد/أوتشا)", occupied: "الجولان السوري محتل منذ ١٩٦٧", besieged: "رفع الحصارات الكبرى بعد ٢٠٢٤ وبقاء اقتتال جيوب", fragLevel: "حرج", fragNote: "مخاطر تشرذم طائفي وإثني في الساحل والجنوب ضمن التحول الهش", hosting: "—", sourceLabel: "ReliefWeb — سوريا", sourceUrl: "https://reliefweb.int/country/syr" },
    { country: "فلسطين", colors: "#161616,#f5f0e6,#007a3d", status: "حرب واحتلال مستمر", displaced: "نحو ١.٩ مليون — ٩٠٪ من سكان غزة نزحوا", refugeesOut: "٥.٩ مليون لاجئ مسجل لدى الأونروا", deaths: "أكثر من ٤٦ ألفًا موثقًا في غزة ونحو ألف بالضفة (OCHA)", occupied: "الضفة الغربية والقدس الشرقية محتلتان منذ ١٩٦٧", besieged: "غزة تحت حصار شامل منذ ٢٠٠٧", fragLevel: "مرتفع", fragNote: "انقسام سياسي فلسطيني ممتد منذ ٢٠٠٧ ومساعي مصالحة متعثرة", hosting: "—", sourceLabel: "ReliefWeb — الأرض الفلسطينية المحتلة", sourceUrl: "https://reliefweb.int/country/pse" },
    { country: "السودان", colors: "#d21034,#f5f0e6,#161616", status: "حرب أهلية شاملة", displaced: "١١.٥ مليون داخليًا — أكبر أزمة نزوح في العالم", refugeesOut: "٤.١ مليون فروا للخارج", deaths: "تقديرات مستقلة تتجاوز ١٥٠ ألفًا (ACLED/خبراء)", occupied: "مناطق واسعة بيد الدعم السريع في دارفور", besieged: "الفاشر محاصرة وتجريد المدنيين الغذاء", fragLevel: "حرج", fragNote: "حكومتان متوازيتان وتفكيك مؤسسي ومخاطر تقسيم عرقي بدارفور", hosting: "—", sourceLabel: "ReliefWeb — السودان", sourceUrl: "https://reliefweb.int/country/sdn" },
    { country: "اليمن", colors: "#ce1126,#f5f0e6,#161616", status: "حرب وتجميد هش", displaced: "٤.٥ مليون نازح داخلي", refugeesOut: "نحو ١٠٠ ألف بالجوار", deaths: "٣٧٧ ألفًا مباشرة وغير مباشرة (UNDP)", occupied: "حكم أمر واقع في صنعاء ومناطق النفوذ المنقسمة", besieged: "تعز تحت حصار جزئي منذ ٢٠١٥", fragLevel: "حرج", fragNote: "ثلاثة مراكز سلطة فعلية وانفصالية جنوبية وانهيار اقتصادي", hosting: "—", sourceLabel: "ReliefWeb — اليمن", sourceUrl: "https://reliefweb.int/country/yem" },
    { country: "الصومال", colors: "#4189de,#2f6fc0,#4189de", status: "تمرد داخلي وجفاف", displaced: "٣.٨ مليون نازح داخلي", refugeesOut: "نحو ٧٠٠ ألف بجوار الجوار", deaths: "نحو ٧ آلاف سنويًا بفعل العنف (ACLED)", occupied: "ريف واسع تحت سيطرة حركة الشباب", besieged: "بلدات حدودية تُحاصر دوريًا", fragLevel: "حرج", fragNote: "انفصال فعلي لأرض الصومال ونزاعات عشائرية وفيدرالية", hosting: "—", sourceLabel: "ReliefWeb — الصومال", sourceUrl: "https://reliefweb.int/country/som" },
    { country: "ليبيا", colors: "#e70013,#161616,#239e46", status: "انقسام مؤسسي مجمّد", displaced: "نحو ١٢٥ ألف نازح داخلي", refugeesOut: "~٥٠ ألف مهاجر ولاجئ مسجل", deaths: "نحو ٣٠ ألفًا منذ ٢٠١١ (تقديرات تراكمية)", occupied: "مناطق نفوذ ميليشياوي متداخل بين معسكرين", besieged: "خط تماس سرت–الجفرة مجمّد منذ ٢٠٢٠", fragLevel: "حرج", fragNote: "حكومتان متنافستان وميليشيات وتدخلات مرتزقة", hosting: "—", sourceLabel: "CFR Conflict Tracker", sourceUrl: "https://www.cfr.org/global-conflict-tracker/conflict/instability-libya" },
    { country: "لبنان", colors: "#ee161f,#f5f0e6,#ee161f", status: "هدنة هشة بعد حرب ٢٠٢٤", displaced: "٩٦ ألف متبقٍ بعد عودة معظم النازحين", refugeesOut: "يستضيف ~٨٠٠ ألف لاجئ سوري مسجل", deaths: "٤٬٠٤٧ قتيلًا في حرب ٢٠٢٤ (وزارة الصحة)", occupied: "مزارع شبعا وتلال كفرشوبا محتلة", besieged: "خروقات شبه يومية جنوب الليطاني", fragLevel: "مرتفع", fragNote: "شغور مؤسسي مزمن وانهيار مصرفي غير مسبوق", hosting: "~٨٠٠ ألف سوري مسجل", sourceLabel: "ReliefWeb — لبنان", sourceUrl: "https://reliefweb.int/country/lbn" },
    { country: "العراق", colors: "#ce1126,#f5f0e6,#161616", status: "استقرار هش بعد داعش", displaced: "١.١ مليون نازح متبقٍ داخليًا", refugeesOut: "—", deaths: "٢٠٠–٦٠٠ ألف منذ ٢٠٠٣ (تقديرات متباينة)", occupied: "لا يوجد احتلال حالي — استرداد مناطق داعش كاملة", besieged: "لا يوجد", fragLevel: "مرتفع", fragNote: "محاصصة إثنية-طائفية دستورية وتوتر اتحادي-كردي", hosting: "~٣٠٠ ألف لاجئ سوري بإقليم كردستان", sourceLabel: "ReliefWeb — العراق", sourceUrl: "https://reliefweb.int/country/irq" },
    { country: "مصر", colors: "#ce1126,#f5f0e6,#161616", status: "مستقر — تأمين شامل", displaced: "لا نزوح داخلي", refugeesOut: "—", deaths: "— (عمليات استباقية محدودة بشمال سيناء)", occupied: "سيادة كاملة على التراب الوطني", besieged: "لا يوجد", fragLevel: "مستقر", fragNote: "لحمة وطنية متماسكة تحت مظلة المؤسسات الدستورية", hosting: "نحو نصف مليون مسجل لدى UNHCR وتقدير رسمي أعلى", sourceLabel: "UNHCR — مصر", sourceUrl: "https://www.unhcr.org/countries/egypt" },
    { country: "الأردن", colors: "#161616,#f5f0e6,#007a3d", status: "مستقر — دولة استضافة", displaced: "لا نزوح داخلي", refugeesOut: "—", deaths: "—", occupied: "لا يوجد", besieged: "لا يوجد", fragLevel: "مستقر", fragNote: "تماسك داخلي رغم ضغط إقليمي اقتصادي", hosting: "١.٣ مليون سوري + ٢.٤ مليون فلسطيني مسجل (UNRWA)", sourceLabel: "UNHCR — الأردن", sourceUrl: "https://www.unhcr.org/countries/jordan" },
    { country: "الجزائر", colors: "#006233,#f5f0e6,#d21034", status: "مستقر", displaced: "لا نزوح داخلي", refugeesOut: "—", deaths: "—", occupied: "لا يوجد", besieged: "لا يوجد", fragLevel: "منخفض", fragNote: "توترات اجتماعية محدودة تحت السيطرة", hosting: "١٧٣ ألف لاجئ صحراوي بمخيمات تندوف", sourceLabel: "ReliefWeb — الجزائر", sourceUrl: "https://reliefweb.int/country/dza" },
    { country: "المغرب", colors: "#c1272d,#a4202a,#c1272d", status: "نزاع سيادة مجمّد", displaced: "لا نزوح داخلي", refugeesOut: "—", deaths: "— (مناوشات محدودة عبر الجدار)", occupied: "نزاع سيادة قائم على الصحراء الغربية", besieged: "خط الدفاع الرملي وتبادل مناوشات", fragLevel: "منخفض", fragNote: "ملف إقليمي ممتد منذ ١٩٧٥ تحت وساطة دولية", hosting: "نحو ٢٠ ألف لاجئ ومهاجر مسجل", sourceLabel: "ReliefWeb — الصحراء الغربية", sourceUrl: "https://reliefweb.int/country/esh" },
    { country: "السعودية", colors: "#006c35,#0b7a3d,#006c35", status: "مستقر — تأمين الحدود الجنوبية", displaced: "لا نزوح داخلي", refugeesOut: "—", deaths: "— (حوادث حدودية متقطعة بالجنوب سابقًا)", occupied: "لا يوجد", besieged: "لا يوجد", fragLevel: "منخفض", fragNote: "استقرار داخلي ومراقبة التهديدات العابرة", hosting: "استضافة إنسانية لأعداد يمنية تاريخية", sourceLabel: "CFR Conflict Tracker", sourceUrl: "https://www.cfr.org/global-conflict-tracker" },
    { country: "تونس", colors: "#e70013,#c8102e,#e70013", status: "مستقر", displaced: "لا نزوح داخلي", refugeesOut: "—", deaths: "— (عمليات إرهابية متقطعة سابقة)", occupied: "لا يوجد", besieged: "لا يوجد", fragLevel: "منخفض", fragNote: "توازن مؤسسي رغم الضغط الاقتصادي", hosting: "نحو ١٠ آلاف لاجئ ومهاجر مسجل", sourceLabel: "ReliefWeb — تونس", sourceUrl: "https://reliefweb.int/" },
    { country: "الكويت", colors: "#007a3d,#f5f0e6,#ce1126", status: "مستقر", displaced: "لا نزوح داخلي", refugeesOut: "—", deaths: "—", occupied: "لا يوجد", besieged: "لا يوجد", fragLevel: "مستقر", fragNote: "وفاق اجتماعي قائم على الأطر الدستورية", hosting: "—", sourceLabel: "UNHCR", sourceUrl: "https://www.unhcr.org/" },
    { country: "الإمارات", colors: "#00732f,#f5f0e6,#161616", status: "مستقر", displaced: "لا نزوح داخلي", refugeesOut: "—", deaths: "— (استهداف مسيّر صُدّ في ٢٠٢٢)", occupied: "لا يوجد", besieged: "لا يوجد", fragLevel: "مستقر", fragNote: "تماسك مجتمعي فيصله دولة المؤسسات", hosting: "استضافة دول الحماية الدولية عدد يقارب الآلاف", sourceLabel: "UNHCR", sourceUrl: "https://www.unhcr.org/" },
    { country: "قطر", colors: "#8a1538,#6e102c,#8a1538", status: "مستقر", displaced: "لا نزوح داخلي", refugeesOut: "—", deaths: "— (قصف إيراني على قاعدة العديد ٢٠٢٥ صُدّ دون خسائر)", occupied: "لا يوجد", besieged: "لا يوجد", fragLevel: "مستقر", fragNote: "محورية أمنية بفعل القاعدة الأمريكية والوساطة الإقليمية", hosting: "—", sourceLabel: "CFR Conflict Tracker", sourceUrl: "https://www.cfr.org/global-conflict-tracker" },
    { country: "البحرين", colors: "#f5f0e6,#ce1126,#ce1126", status: "مستقر", displaced: "لا نزوح داخلي", refugeesOut: "—", deaths: "—", occupied: "لا يوجد", besieged: "لا يوجد", fragLevel: "منخفض", fragNote: "حمائية أمنية مع حلفاء المجلس", hosting: "—", sourceLabel: "UNHCR", sourceUrl: "https://www.unhcr.org/" },
    { country: "عُمان", colors: "#f5f0e6,#db161b,#008000", status: "مستقر — قناة وساطة", displaced: "لا نزوح داخلي", refugeesOut: "—", deaths: "—", occupied: "لا يوجد", besieged: "لا يوجد", fragLevel: "مستقر", fragNote: "دبلوماسية الحياد النشط واستقرار داخلي عتيد", hosting: "—", sourceLabel: "UNHCR", sourceUrl: "https://www.unhcr.org/" },
    { country: "موريتانيا", colors: "#cd2a3e,#006233,#cd2a3e", status: "رصد حدودي مع الساحل", displaced: "لا نزوح داخلي", refugeesOut: "—", deaths: "— (عمليات إرهابية شبه منعدمة منذ ٢٠١١)", occupied: "لا يوجد", besieged: "لا يوجد", fragLevel: "منخفض", fragNote: "عضو G5 الساحل وحالة يقظة شراضية للحدود", hosting: "نحو ١٣٠ ألف لاجئ مالي بمخيم امبره", sourceLabel: "UNHCR — موريتانيا", sourceUrl: "https://www.unhcr.org/countries/mauritania" },
    { country: "جيبوتي", colors: "#6ab2e7,#f5f0e6,#12ad2b", status: "مستقر — محور دولي", displaced: "لا نزوح داخلي", refugeesOut: "—", deaths: "—", occupied: "لا يوجد", besieged: "لا يوجد", fragLevel: "مستقر", fragNote: "ضغط جيوسياسي لموقع باب المندب تحت رقابة الدولة", hosting: "نحو ٣٠ ألف لاجئ إقليمي", sourceLabel: "UNHCR — جيبوتي", sourceUrl: "https://www.unhcr.org/" },
    { country: "جزر القمر", colors: "#ffc61e,#f5f0e6,#ce1126", status: "مستقر", displaced: "لا نزوح داخلي", refugeesOut: "—", deaths: "—", occupied: "لا يوجد", besieged: "لا يوجد", fragLevel: "مستقر", fragNote: "وحدة وطنية بعد تدوال التاريخ الانقلابي", hosting: "—", sourceLabel: "UNHCR", sourceUrl: "https://www.unhcr.org/" },
  ]);

  console.log("✅ تمت تهيئة قاعدة البيانات بنجاح.");
  process.exit(0);
}

function monthsAt3() {
  return monthsAgo(3);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
